### ISSUE TITLE
Automatic Building and Release of the Android App

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-installer-android#151]
## Overview 

Allow new releases of the Android App to be automatically built, properly versioned, and uploaded to the Play Store

```[tasklist]
### Tasks
- [x] Create scripting/tooling to access the Google Play Store Developer APIs and fetch information about the latest releases - use this to calculate the next numeric versionCode that should be used for this production release.
- [x] Update our version tooling to set the versionCode once during a build cycle, using either the above script, or the time based versionCode for development builds, rather than recalculating with a function call.
- [x] Tweak the versioning scheme to return `"debug"` by default instead of `"unknown"` as the final parameter
- [x] Tweak the versioning to read the installer version from a local code constant instead of git tags
- [x] Replace "-official" in the displayed version on the loading page with ""
- [x] Modify the Github action to take both production and development signing key secrets
- [x] Modify the Github action to take Google Play API access secret
- [x] Modify the Github Action to accept a release parameter which will toggle between the production and development signing key secrets
- [x] Use the same release parameter to toggle between building an APK and an AAB
- [x] For the APK build, return the APK filename as the output
- [x] For the release build, upload the AAB to an internal testing track on the Play Store, and then download the universal APK to use as the output
- [x] Return the versionCode from the build also - in the case of the APK, this will not be used, but for the AAB upload, this can be used to promote the internal release to a beta release
- [x] Create an additional Github Action that takes the versionCode and uses Google Play API access secrets and then promotes that versionCode from the internal release track to the beta testing release track - this action should read the existing releases and find the existing internal track release in order to generate the release on the beta track.
```

**Comment by rtibbles** [comment]
Fixed in #152
